### ISSUE TITLE
Error deploying Stream Example App in Heroku

### ISSUE THREAD

**Issue by JoseBluenet** [GetStream/Stream-Example-Nodejs#1]
At the moment it is not possible to deploy the "Stream-Example-Nodejs" application in Heroku.
During the deployment I get the error below.

[GetStream/Stream-Example-Nodejs](https://github.com/GetStream/Stream-Example-Nodejs) 
https://github.com/GetStream/Stream-Example-Nodejs

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/app/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

```

<img width="1209" alt="streamexampleapp_error_heroku" src="https://cloud.githubusercontent.com/assets/13038624/10851643/8b2e2048-7f2c-11e5-836e-d52588b0e9ba.png">

**Comment by tbarbugli** [comment]
thank you for reporting this. we are going to have a look at this. in the meantime let us know if you find anything about the issue ;)

**Comment by tbarbugli** [comment]
seems like Heroku had some issues in the last few days. everything seems to be working OK again. please reopen this ticket if you still have issues.

**Comment by SamTharani** [comment]
Hi
I try this one by using npm "install inside node_modules/mongodb" after that it is started to run but its still show 
[Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

but now I can deploy the project
