### ISSUE TITLE
Got error when run ./after_deploy.js

### ISSUE THREAD

**Issue by SamTharani** [GetStream/Stream-Example-Nodejs#6]
Hi all
I try to run "after_deploy.js" from the root directory of the project during this process I got an issue as
module.js:341
    throw err;
    ^
Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/samantha/Projects/react-sample-projects/Stream-Example-Nodejs/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
can anyone help me to resolve this 

Thank you

**Comment by ajbeach2** [comment]
run:
```bash
npm install --save mongoose@latest
```

See if that fixes your issue. Also see https://github.com/Automattic/mongoose/issues/2718

**Comment by matthisk** [comment]
Latest commit on master should fix this issue (I downgraded mongoose to 3.8). Please reopen if you are still experiencing the same issue.
