### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by jholt1** [GetStream/Stream-Example-Nodejs#8]
There seems to be an issue with getting it to deploy on heroku `Postdeploy exit code was not 0`

```
Starting import with User admin

/app/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:325:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:173:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Nisthar** [comment]
Same here

**Comment by nparsons08** [comment]
Issue resolved. Sorry for the delay!
